In [18]:
import numpy as np
from sklearn.datasets import load_iris

In [4]:
a1=np.ones((2,3))
print(a1)

a2=np.zeros((2,2))
print(a2)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


In [5]:
b1=np.ones((2,3))
b1
b2=np.zeros((3,3))

In [10]:
#dstack : 행, 열이 아닌 깊이(depth) 방향으로 배열을 합친다.
#가장 안쪽 원소에 대한 차원이 증가한다.
c1=np.ones((3,4))
c2=np.zeros((3,4))
#dstack을 하면 (3,4,2)가 된다. (두 면이 포개어 진다고 생각하면됨)
k=np.dstack([c1,c2])

In [14]:
print(k)
k.shape

[[[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]]


(3, 4, 2)

In [17]:
#axis=1 이면, 두번째 차원으로 새로운 차원이 삽입.
c=np.stack([c1,c2],axis=1) # 2개의 (3,4) => (3,2,4)가 된다.
print(c)
c.shape

[[[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]]


(3, 2, 4)

In [30]:
iris=load_iris()
len(iris['data'])

150

In [36]:
x=np.arange(1,10001)
y=np.arange(10001,20001)
z=np.zeros_like(x)
for i in range(10000): #for문 연산
    z[i]=x[i]+y[i]

In [38]:
z=x+y #벡터화 연산(요소 단위로 연산)
z

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

In [42]:
a=np.array([1,2,3,4])
b=np.array([4,2,3,4])
c=np.array([1,2,3,4])
print(a==b) #벡터화 연산을 통해 각 요소 별 비교 연산을 수행.
print(np.all(a==b)) #모든 원소가 같나?  False
print(np.all(a==c)) #모든 원소가 같나? True

[False  True  True  True]
False
True


In [43]:
x=np.arange(5)
np.exp(x) #exp() :: exponent(자연상수) : 2.718
            #exp(n) :: 2.718의 n승 값을 리턴함.

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [44]:
10**x #벡터화 연산 가능

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [45]:
x=np.arange(10)
100*x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [47]:
x=np.arange(12).reshape(3,4)
100*x # 스칼라 * 행렬

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [48]:
#브로드캐스팅 :: 크기가 서로 다른 두 배열이 연산이 가능하도록 확장 (크기를 맞춘다. / 확장만 가능, 축소는 불가능)
x=np.arange(5)
y=np.ones_like(x)
x+1 #브로드캐스팅을 함. array([1,1,1,1,1]) 형태로 변형되어 벡터연산을 함.

array([1, 2, 3, 4, 5])

In [56]:
x=np.vstack([range(7)[i:i+3] for i in range(5) ])
print(x)
y=np.arange(5)[:,np.newaxis] # newaxis :: 새로운 축을 하나 추가
print(y)
x+y

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
[[0]
 [1]
 [2]
 [3]
 [4]]


array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [68]:
x=np.array([51,32,43,74])
np.sum(x) #x의 모든 요소의 합
x.sum() # 위와 같은 결과가 나옴.
x.argmin() # x의 요소들중 가장 작은 값의 index를 반환.
x.argmax()
x.mean()
np.median(x)
np.all([True,True,False,True])
np.any([True,False,False]) #하나라도 True 값을 가지면 True가 반환됨.

False

10행 5열(2차원) -> 행평균 -> 10개의 수치(1차원) //차원 축소가 일어남

In [69]:
a=np.array([1,2,3,2])
b=np.array([2,2,3,2])
c=np.array([6,4,4,5])

((a<=b) & (b<=c)).all()

True