    Numpy
    Python:: list의 단점 : 속도가 느리다, 메모리를 많이 차지한다.
    Numpy :: array 장점 : 속도가 빠르다, 메모리를 적게 차지한다.
    리스트는 모든 원소의 자료형이 같지 않아도 된다.
    array는 모든 원소의 자료형이 같아야 된다, 원소의 개수를 바꿀 수 없다.

1) Numpy의 정의
* 수치 연산 패키지이다.
* 선형대수(벡터, 행렬) 연산에서 사용됨.
* 벡터화 연산을 지원 => 연산 속도가 빠름, 코드도 간단~
* [선형대수] : 데이터를 다루는 방법을 표현한 수식, 데이터를 분해, 데이터 분석 기초.
* 행렬의 곱셈을 이용하여 데이터를 조작
* 역행렬을 이용한 회구분석에 활용

In [1]:
import numpy as np

In [10]:
arr=np.array([1,2,3,4]) #array() 리스트를 인자로 보내면 배열이 만들어짐.
arr
arr2=np.array([0,1,2.5]) #integer & float 를 둘 다 써도 정수=> 실수로 자동 형변환이 이뤄짐.
#숫자의 경우 섞어 써도 상관 없다.
arr2
arr3=np.array([0,1,True]) 
#"문자"가 섞여있으면 모두 문자로 형변환됨.
#"실수"가 섞여 있으면 모두 실수형으로 형변환 됨.
#"정수"가 섞여 있으면 모두 정수형으로 형변환 됨.
# 형변환 우선순위 : 문자 > 실수 > 정수 > 불린
arr3


array([0, 1, 1])

In [11]:
type(arr) #numpy.ndarray(n-차원 배열)

numpy.ndarray

In [20]:
#벡터화 연산 : 배열의 각 요소에 대한 반복 연산을 하나의 명령어로 빠르게 처리.
data=list(range(0,10))

#data의 값을 모두 2배 한 다음 answer에 저장 한 후 출력
answer=[]
for x in data:
    answer.append(x*2)
answer

x=np.array(data)
y=x*2 #벡터화 연산// x의 각 요소에 곱하기 2한 값을 y에 저장.
y

#리스트에서 *2를 하면 요소가 두번 반복적으로 출력, 배열*2는 배열의 각 요소에 두배를 하라는 의미


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
a=np.array([1,2,3])
b=np.array([10,20,30])
2*a+b
a==2 # 각 요소들이 2인지를 모두 확인
(a==2) & (b>10) #a와 b에 대해서 and 연산을 해줌

array([False,  True, False])

In [27]:
a2=[1,2,3]
b2=[4,5,6]
a2+b2 # //리스트는 결합 연산이 수행됨.
a2==2 # a2 변수에 저장된 값이 2 인가? False

False

    0차원 array : Scala
    1차원 array : Vector
    2차원 array : Matrix

In [43]:
c=np.array([[0,1,2],[3,4,5]]) #2차원 배열(2행 3열)
print(c)
len(c) #행이 몇개 인지 출력됨.
len(c[0]) #열이 몇개 인지 출력됨.
d=np.array(list(range(1,25))) # 1x24 행렬
d.reshape(6,4) # 6x4 행렬



[[0 1 2]
 [3 4 5]]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [48]:
d=d.reshape(2,3,4) # 2행 3열, 깊이 4
len(d[0][0])

4

In [51]:
a=np.array([1,2,3])
print(a.ndim)
a.shape

1


(3,)

In [66]:
c=np.array([[0,1,2],[3,4,5]])
print(c.ndim)
c.shape
c[1,2]
c[-1,-1] #마지막 행의 마지막 열 == c[1,2]
c[:,1] #모든 행의 1번 열
c[1,1:] #두번째 행의 두번째 열부터 마지막 열까지

2


array([4, 5])

In [55]:
d.ndim
d.shape

(2, 3, 4)

In [57]:
a=np.array([1,2,3,4,5])
a[-2]

4

In [70]:
c[:1,] #0번째 행까지 모든 열을 추출
c[:1 , :1] #0번 행까지 0번 열까지 추출

array([[0]])

In [76]:
a=np.array([0,1,2,3])
idx=np.array([True, False, True, False])
a[idx] #a의 값들 중에서 idx에서 True에 해당하는 값들 만 추출됨.
#Index Error가 발생될 수 있으므로 주의(크기가 동일해야됨.)

a%2 #array([0,1,0,1])
a%2==0 #array([True, False, True, False])
a[a%2==0] #True에 해당하는 값들만 추출 (불린 추출)

array([0, 2])

In [77]:
a=np.array([10,20,30,40,50])
idx=np.array([0,2,4]) #index 지정.
a[idx]

array([10, 30, 50])

In [78]:
#연습문제
m=np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
print(m[1,2])
print(m[-1,-1])
print(m[1,1:3])
print(m[1:,2])
print(m[:2, 3:])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


In [94]:
a=np.array(list(range(1,13)))
a=a.reshape(3,4)
a[:,[True, True, False,True]] #boolean값을 주고 추출이 가능하다.
a[[True, False,True],:]
a[[2,0,1],:] #2-0-1행 순서로 참조해라.


array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [98]:
x=np.array([1,2,3])
x.dtype
x=np.array([1.1,2.1,3.1])
x.dtype #x에 저장된 데이터의 타입을 반한

dtype('float64')

In [99]:
x=np.array([1,2,3.14])
x.dtype # 자동으로 형변환이 이뤄지기 때문에 dtype은 float으로 나온다.

dtype('float64')

In [106]:
x=np.array([1,2,3],dtype="float") #dtype옵션으로 명시하면 직접 타입을 줄수있다.

In [108]:
x[0]+x[1]

3

In [109]:
x=np.array([0,1,-1,0])
y=np.array([1,0,0,0])
x/y #array([  0.,  inf, -inf,  nan]) // 0, 양의 무한, 음의 무한, nan(0은 분모가 될수 없으므로)
#inf: 무한대 , nan : not a number(정의할 수 없는 숫자)

C:\Users\B-17\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\B-17\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([  0.,  inf, -inf,  nan])

In [113]:
np.log(0)

C:\Users\B-17\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [115]:
x=np.zeros(3) #0이 3개가 들어있는 배열이 생성됨.
x

array([0., 0., 0.])

In [122]:
x=np.zeros((2,3),dtype="i") #0이 2x3개가 들어있는 2차원 배열이 생성됨. , dtype부여 가능.(약자사용가능)
x.dtype
x

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [126]:
y=np.zeros_like(a) #a와 같은 구조(2행 3열)로 만들되 0으로 초기화 해라.
y

In [129]:
x=np.ones((2,3,4)) #2행 3열 4깊이
x

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [131]:
z=np.ones_like(y) #y랑 같은 구조로 만들고 그 안을 1로 채운다.
z

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [135]:
#range: python, arragne: Numpy
np.arange(2,11,3)

array([2, 5, 8])

In [136]:
np.linspace(0,100,5) #선형공간(시작값, 끝값, 개수)

array([  0.,  25.,  50.,  75., 100.])

In [137]:
a=np.array([[1,2,3],[4,5,6]])
a.T #transpose: 행과 열을 교환

array([[1, 4],
       [2, 5],
       [3, 6]])

In [150]:
a=np.arange(12)
a.reshape(3,-1) #3x4와 같은 결과가 나옴. (-1)의 의미 : 나머지를 가지고 열은 알아서 판단해줌.
a.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [155]:
a=a.reshape(2,-1,2)
a.shape
#1차원 데이터를 다른 차원으로 변환할때는 reshape함수를 사용한다.
print(a)

# flatten() :: n차원을 1차원으로 변환하는 함수 
# ravel() :: n차원을 1차원으로 변환하는 함수
a.flatten()
a.ravel()

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [160]:
x=np.arange(5) #1차원
x=x.reshape(1,5) #2차원
x.flatten() #1차원

array([0, 1, 2, 3, 4])

In [164]:
x=x.reshape(5,1)
x
#x.flatten()

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [173]:
x=np.arange(5) #1차원
x

array([0, 1, 2, 3, 4])

In [174]:
x=x[:, np.newaxis] #배열에 대한 차원을 1만큼 증가
x.shape

(5, 1)

In [176]:
#배열 연결
#hstack: 행의 수가 같은 배열을 옆으로 연결(horizonal)
#vstack: (vertical)
x1=np.ones((2,3))
x1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [178]:
#배열 연결
#hstack: 행의 수가 같은 배열을 옆으로 연결(horizonal)
#vstack: 열의 수가 같은 배열을 수직으로 연결(vertical)
x2=np.zeros((2,2))
x2

array([[0., 0.],
       [0., 0.]])

In [180]:
np.hstack([x2,x1])
np.hstack([x1,x2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [183]:
x3=np.ones((3,2))
np.vstack([x2,x3])
np.vstack([x3,x2])

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.]])